const std = @import("std");

const InstructionTag = @import("./instruction_tag.zig").InstructionTag;

pub const Export = struct {
    pub const DescritionType = enum {
        function,
        table,
        memory,
        global,
    };

    index: u32,
    name: []const u8,
    type: DescritionType,
};

pub const FunctionType = struct {
    parameters: []ValueType,
    results: []ValueType,
};

pub const Module = struct {
    area: std.heap.ArenaAllocator,

    exports: []Export,
    function_types: []FunctionType,
    function_type_indices: []u32,
    function_bodies: []FunctionBody,

    const Self = @This();

    pub fn findExportedFunctionIndex(self: *const Self, name: []const u8) ?u32 {
        for (self.exports) |e| {
            if (e.type == .function and std.mem.eql(u8, name, e.name)) {
                return e.index;
            }
        }

        return null;
    }

    pub fn deinit(self: Self) void {
        self.area.deinit();
    }
};

pub const FunctionBody = struct {
    locals: []Local,
    expression: []Instruction,
};

const Tuple = std.meta.Tuple;
const EmptyTuple: type = Tuple(&[_]type{});

pub const Local = struct {
    n: u32,
    type: ValueType,
};

pub const ValueType = enum {
    i32,
    i64,
    f32,
    f64,
    v128,
    function_reference,
    extern_reference,
};

pub const Instruction = union(InstructionTag) {
    @"unreachable": EmptyTuple,
    nop: EmptyTuple,
    block: EmptyTuple,
    loop: EmptyTuple,
    @"if": EmptyTuple,
    @"else": EmptyTuple,
    end: EmptyTuple,
    br: Tuple(&[_]type{u32}),
    br_if: Tuple(&[_]type{u32}),
    br_table: EmptyTuple,
    @"return": EmptyTuple,
    call: EmptyTuple,
    call_indirect: EmptyTuple,
    drop: EmptyTuple,
    select: EmptyTuple,
    select_t: EmptyTuple,
    @"local.get": Tuple(&[_]type{u32}),
    @"local.set": Tuple(&[_]type{u32}),
    @"local.tee": Tuple(&[_]type{u32}),
    @"global.get": Tuple(&[_]type{u32}),
    @"global.set": Tuple(&[_]type{u32}),
    @"table.get": EmptyTuple,
    @"table.set": EmptyTuple,
    @"i32.load": EmptyTuple,
    @"i64.load": EmptyTuple,
    @"f32.load": EmptyTuple,
    @"f64.load": EmptyTuple,
    @"i32.load8_s": EmptyTuple,
    @"i32.load8_u": EmptyTuple,
    @"i32.load16_s": EmptyTuple,
    @"i32.load16_u": EmptyTuple,
    @"i64.load8_s": EmptyTuple,
    @"i64.load8_u": EmptyTuple,
    @"i64.load16_s": EmptyTuple,
    @"i64.load16_u": EmptyTuple,
    @"i64.load32_s": EmptyTuple,
    @"i64.load32_u": EmptyTuple,
    @"i32.store": EmptyTuple,
    @"i64.store": EmptyTuple,
    @"f32.store": EmptyTuple,
    @"f64.store": EmptyTuple,
    @"i32.store8": EmptyTuple,
    @"i32.store16": EmptyTuple,
    @"i64.store8": EmptyTuple,
    @"i64.store16": EmptyTuple,
    @"i64.store32": EmptyTuple,
    @"memory.size": EmptyTuple,
    @"memory.grow": EmptyTuple,
    @"i32.const": Tuple(&[_]type{i32}),
    @"i64.const": Tuple(&[_]type{i64}),
    @"f32.const": Tuple(&[_]type{f32}),
    @"f64.const": Tuple(&[_]type{f64}),
    @"i32.eqz": EmptyTuple,
    @"i32.eq": EmptyTuple,
    @"i32.ne": EmptyTuple,
    @"i32.lt_s": EmptyTuple,
    @"i32.lt_u": EmptyTuple,
    @"i32.gt_s": EmptyTuple,
    @"i32.gt_u": EmptyTuple,
    @"i32.le_s": EmptyTuple,
    @"i32.le_u": EmptyTuple,
    @"i32.ge_s": EmptyTuple,
    @"i32.ge_u": EmptyTuple,
    @"i64.eqz": EmptyTuple,
    @"i64.eq": EmptyTuple,
    @"i64.ne": EmptyTuple,
    @"i64.lt_s": EmptyTuple,
    @"i64.lt_u": EmptyTuple,
    @"i64.gt_s": EmptyTuple,
    @"i64.gt_u": EmptyTuple,
    @"i64.le_s": EmptyTuple,
    @"i64.le_u": EmptyTuple,
    @"i64.ge_s": EmptyTuple,
    @"i64.ge_u": EmptyTuple,
    @"f32.eq": EmptyTuple,
    @"f32.ne": EmptyTuple,
    @"f32.lt": EmptyTuple,
    @"f32.gt": EmptyTuple,
    @"f32.le": EmptyTuple,
    @"f32.ge": EmptyTuple,
    @"f64.eq": EmptyTuple,
    @"f64.ne": EmptyTuple,
    @"f64.lt": EmptyTuple,
    @"f64.gt": EmptyTuple,
    @"f64.le": EmptyTuple,
    @"f64.ge": EmptyTuple,
    @"i32.clz": EmptyTuple,
    @"i32.ctz": EmptyTuple,
    @"i32.popcnt": EmptyTuple,
    @"i32.add": EmptyTuple,
    @"i32.sub": EmptyTuple,
    @"i32.mul": EmptyTuple,
    @"i32.div_s": EmptyTuple,
    @"i32.div_u": EmptyTuple,
    @"i32.rem_s": EmptyTuple,
    @"i32.rem_u": EmptyTuple,
    @"i32.and": EmptyTuple,
    @"i32.or": EmptyTuple,
    @"i32.xor": EmptyTuple,
    @"i32.shl": EmptyTuple,
    @"i32.shr_s": EmptyTuple,
    @"i32.shr_u": EmptyTuple,
    @"i32.rotl": EmptyTuple,
    @"i32.rotr": EmptyTuple,
    @"i64.clz": EmptyTuple,
    @"i64.ctz": EmptyTuple,
    @"i64.popcnt": EmptyTuple,
    @"i64.add": EmptyTuple,
    @"i64.sub": EmptyTuple,
    @"i64.mul": EmptyTuple,
    @"i64.div_s": EmptyTuple,
    @"i64.div_u": EmptyTuple,
    @"i64.rem_s": EmptyTuple,
    @"i64.rem_u": EmptyTuple,
    @"i64.and": EmptyTuple,
    @"i64.or": EmptyTuple,
    @"i64.xor": EmptyTuple,
    @"i64.shl": EmptyTuple,
    @"i64.shr_s": EmptyTuple,
    @"i64.shr_u": EmptyTuple,
    @"i64.rotl": EmptyTuple,
    @"i64.rotr": EmptyTuple,
    @"f32.abs": EmptyTuple,
    @"f32.neg": EmptyTuple,
    @"f32.ceil": EmptyTuple,
    @"f32.floor": EmptyTuple,
    @"f32.trunc": EmptyTuple,
    @"f32.nearest": EmptyTuple,
    @"f32.sqrt": EmptyTuple,
    @"f32.add": EmptyTuple,
    @"f32.sub": EmptyTuple,
    @"f32.mul": EmptyTuple,
    @"f32.div": EmptyTuple,
    @"f32.min": EmptyTuple,
    @"f32.max": EmptyTuple,
    @"f32.copysign": EmptyTuple,
    @"f64.abs": EmptyTuple,
    @"f64.neg": EmptyTuple,
    @"f64.ceil": EmptyTuple,
    @"f64.floor": EmptyTuple,
    @"f64.trunc": EmptyTuple,
    @"f64.nearest": EmptyTuple,
    @"f64.sqrt": EmptyTuple,
    @"f64.add": EmptyTuple,
    @"f64.sub": EmptyTuple,
    @"f64.mul": EmptyTuple,
    @"f64.div": EmptyTuple,
    @"f64.min": EmptyTuple,
    @"f64.max": EmptyTuple,
    @"f64.copysign": EmptyTuple,
    @"i32.wrap_i64": EmptyTuple,
    @"i32.trunc_f32_s": EmptyTuple,
    @"i32.trunc_f32_u": EmptyTuple,
    @"i32.trunc_f64_s": EmptyTuple,
    @"i32.trunc_f64_u": EmptyTuple,
    @"i64.extend_i32_s": EmptyTuple,
    @"i64.extend_i32_u": EmptyTuple,
    @"i64.trunc_f32_s": EmptyTuple,
    @"i64.trunc_f32_u": EmptyTuple,
    @"i64.trunc_f64_s": EmptyTuple,
    @"i64.trunc_f64_u": EmptyTuple,
    @"f32.convert_i32_s": EmptyTuple,
    @"f32.convert_i32_u": EmptyTuple,
    @"f32.convert_i64_s": EmptyTuple,
    @"f32.convert_i64_u": EmptyTuple,
    @"f32.demote_f64": EmptyTuple,
    @"f64.convert_i32_s": EmptyTuple,
    @"f64.convert_i32_u": EmptyTuple,
    @"f64.convert_i64_s": EmptyTuple,
    @"f64.convert_i64_u": EmptyTuple,
    @"f64.promote_f32": EmptyTuple,
    @"i32.reinterpret_f32": EmptyTuple,
    @"i64.reinterpret_f64": EmptyTuple,
    @"f32.reinterpret_i32": EmptyTuple,
    @"f64.reinterpret_i64": EmptyTuple,
    @"i32.extend8_s": EmptyTuple,
    @"i32.extend16_s": EmptyTuple,
    @"i64.extend8_s": EmptyTuple,
    @"i64.extend16_s": EmptyTuple,
    @"i64.extend32_s": EmptyTuple,
    @"ref.null": EmptyTuple,
    @"ref.is_null": EmptyTuple,
    @"ref.func": EmptyTuple,
    @"i32.trunc_sat_f32_s": EmptyTuple,
    @"i32.trunc_sat_f32_u": EmptyTuple,
    @"i32.trunc_sat_f64_s": EmptyTuple,
    @"i32.trunc_sat_f64_u": EmptyTuple,
    @"i64.trunc_sat_f32_s": EmptyTuple,
    @"i64.trunc_sat_f32_u": EmptyTuple,
    @"i64.trunc_sat_f64_s": EmptyTuple,
    @"i64.trunc_sat_f64_u": EmptyTuple,
    @"memory.init": EmptyTuple,
    @"data.drop": EmptyTuple,
    @"memory.copy": EmptyTuple,
    @"memory.fill": EmptyTuple,
    @"table.init": EmptyTuple,
    @"elem.drop": EmptyTuple,
    @"table.copy": EmptyTuple,
    @"table.grow": EmptyTuple,
    @"table.size": EmptyTuple,
    @"table.fill": EmptyTuple,
    @"v128.load": EmptyTuple,
    @"v128.load8x8_s": EmptyTuple,
    @"v128.load8x8_u": EmptyTuple,
    @"v128.load16x4_s": EmptyTuple,
    @"v128.load16x4_u": EmptyTuple,
    @"v128.load32x2_s": EmptyTuple,
    @"v128.load32x2_u": EmptyTuple,
    @"v128.load8_splat": EmptyTuple,
    @"v128.load16_splat": EmptyTuple,
    @"v128.load32_splat": EmptyTuple,
    @"v128.load64_splat": EmptyTuple,
    @"v128.store": EmptyTuple,
    @"v128.const": EmptyTuple,
    @"i8x16.shuffle": EmptyTuple,
    @"i8x16.swizzle": EmptyTuple,
    @"i8x16.splat": EmptyTuple,
    @"i16x8.splat": EmptyTuple,
    @"i32x4.splat": EmptyTuple,
    @"i64x2.splat": EmptyTuple,
    @"f32x4.splat": EmptyTuple,
    @"f64x2.splat": EmptyTuple,
    @"i8x16.extract_lane_s": EmptyTuple,
    @"i8x16.extract_lane_u": EmptyTuple,
    @"i8x16.replace_lane": EmptyTuple,
    @"i16x8.extract_lane_s": EmptyTuple,
    @"i16x8.extract_lane_u": EmptyTuple,
    @"i16x8.replace_lane": EmptyTuple,
    @"i32x4.extract_lane": EmptyTuple,
    @"i32x4.replace_lane": EmptyTuple,
    @"i64x2.extract_lane": EmptyTuple,
    @"i64x2.replace_lane": EmptyTuple,
    @"f32x4.extract_lane": EmptyTuple,
    @"f32x4.replace_lane": EmptyTuple,
    @"f64x2.extract_lane": EmptyTuple,
    @"f64x2.replace_lane": EmptyTuple,
    @"i8x16.eq": EmptyTuple,
    @"i8x16.ne": EmptyTuple,
    @"i8x16.lt_s": EmptyTuple,
    @"i8x16.lt_u": EmptyTuple,
    @"i8x16.gt_s": EmptyTuple,
    @"i8x16.gt_u": EmptyTuple,
    @"i8x16.le_s": EmptyTuple,
    @"i8x16.le_u": EmptyTuple,
    @"i8x16.ge_s": EmptyTuple,
    @"i8x16.ge_u": EmptyTuple,
    @"i16x8.eq": EmptyTuple,
    @"i16x8.ne": EmptyTuple,
    @"i16x8.lt_s": EmptyTuple,
    @"i16x8.lt_u": EmptyTuple,
    @"i16x8.gt_s": EmptyTuple,
    @"i16x8.gt_u": EmptyTuple,
    @"i16x8.le_s": EmptyTuple,
    @"i16x8.le_u": EmptyTuple,
    @"i16x8.ge_s": EmptyTuple,
    @"i16x8.ge_u": EmptyTuple,
    @"i32x4.eq": EmptyTuple,
    @"i32x4.ne": EmptyTuple,
    @"i32x4.lt_s": EmptyTuple,
    @"i32x4.lt_u": EmptyTuple,
    @"i32x4.gt_s": EmptyTuple,
    @"i32x4.gt_u": EmptyTuple,
    @"i32x4.le_s": EmptyTuple,
    @"i32x4.le_u": EmptyTuple,
    @"i32x4.ge_s": EmptyTuple,
    @"i32x4.ge_u": EmptyTuple,
    @"f32x4.eq": EmptyTuple,
    @"f32x4.ne": EmptyTuple,
    @"f32x4.lt": EmptyTuple,
    @"f32x4.gt": EmptyTuple,
    @"f32x4.le": EmptyTuple,
    @"f32x4.ge": EmptyTuple,
    @"f64x2.eq": EmptyTuple,
    @"f64x2.ne": EmptyTuple,
    @"f64x2.lt": EmptyTuple,
    @"f64x2.gt": EmptyTuple,
    @"f64x2.le": EmptyTuple,
    @"f64x2.ge": EmptyTuple,
    @"v128.not": EmptyTuple,
    @"v128.and": EmptyTuple,
    @"v128.andnot": EmptyTuple,
    @"v128.or": EmptyTuple,
    @"v128.xor": EmptyTuple,
    @"v128.bitselect": EmptyTuple,
    @"v128.any_true": EmptyTuple,
    @"v128.load8_lane": EmptyTuple,
    @"v128.load16_lane": EmptyTuple,
    @"v128.load32_lane": EmptyTuple,
    @"v128.load64_lane": EmptyTuple,
    @"v128.store8_lane": EmptyTuple,
    @"v128.store16_lane": EmptyTuple,
    @"v128.store32_lane": EmptyTuple,
    @"v128.store64_lane": EmptyTuple,
    @"v128.load32_zero": EmptyTuple,
    @"v128.load64_zero": EmptyTuple,
    @"f32x4.demote_f64x2_zero": EmptyTuple,
    @"f64x2.promote_low_f32x4": EmptyTuple,
    @"i8x16.abs": EmptyTuple,
    @"i8x16.neg": EmptyTuple,
    @"i8x16.popcnt": EmptyTuple,
    @"i8x16.all_true": EmptyTuple,
    @"i8x16.bitmask": EmptyTuple,
    @"i8x16.narrow_i16x8_s": EmptyTuple,
    @"i8x16.narrow_i16x8_u": EmptyTuple,
    @"f32x4.ceil": EmptyTuple,
    @"f32x4.floor": EmptyTuple,
    @"f32x4.trunc": EmptyTuple,
    @"f32x4.nearest": EmptyTuple,
    @"i8x16.shl": EmptyTuple,
    @"i8x16.shr_s": EmptyTuple,
    @"i8x16.shr_u": EmptyTuple,
    @"i8x16.add": EmptyTuple,
    @"i8x16.add_sat_s": EmptyTuple,
    @"i8x16.add_sat_u": EmptyTuple,
    @"i8x16.sub": EmptyTuple,
    @"i8x16.sub_sat_s": EmptyTuple,
    @"i8x16.sub_sat_u": EmptyTuple,
    @"f64x2.ceil": EmptyTuple,
    @"f64x2.floor": EmptyTuple,
    @"i8x16.min_s": EmptyTuple,
    @"i8x16.min_u": EmptyTuple,
    @"i8x16.max_s": EmptyTuple,
    @"i8x16.max_u": EmptyTuple,
    @"f64x2.trunc": EmptyTuple,
    @"i8x16.avgr_u": EmptyTuple,
    @"i16x8.extadd_pairwise_i8x16_s": EmptyTuple,
    @"i16x8.extadd_pairwise_i8x16_u": EmptyTuple,
    @"i32x4.extadd_pairwise_i16x8_s": EmptyTuple,
    @"i32x4.extadd_pairwise_i16x8_u": EmptyTuple,
    @"i16x8.abs": EmptyTuple,
    @"i16x8.neg": EmptyTuple,
    @"i16x8.q15mulr_sat_s": EmptyTuple,
    @"i16x8.all_true": EmptyTuple,
    @"i16x8.bitmask": EmptyTuple,
    @"i16x8.narrow_i32x4_s": EmptyTuple,
    @"i16x8.narrow_i32x4_u": EmptyTuple,
    @"i16x8.extend_low_i8x16_s": EmptyTuple,
    @"i16x8.extend_high_i8x16_s": EmptyTuple,
    @"i16x8.extend_low_i8x16_u": EmptyTuple,
    @"i16x8.extend_high_i8x16_u": EmptyTuple,
    @"i16x8.shl": EmptyTuple,
    @"i16x8.shr_s": EmptyTuple,
    @"i16x8.shr_u": EmptyTuple,
    @"i16x8.add": EmptyTuple,
    @"i16x8.add_sat_s": EmptyTuple,
    @"i16x8.add_sat_u": EmptyTuple,
    @"i16x8.sub": EmptyTuple,
    @"i16x8.sub_sat_s": EmptyTuple,
    @"i16x8.sub_sat_u": EmptyTuple,
    @"f64x2.nearest": EmptyTuple,
    @"i16x8.mul": EmptyTuple,
    @"i16x8.min_s": EmptyTuple,
    @"i16x8.min_u": EmptyTuple,
    @"i16x8.max_s": EmptyTuple,
    @"i16x8.max_u": EmptyTuple,
    @"i16x8.avgr_u": EmptyTuple,
    @"i16x8.extmul_low_i8x16_s": EmptyTuple,
    @"i16x8.extmul_high_i8x16_s": EmptyTuple,
    @"i16x8.extmul_low_i8x16_u": EmptyTuple,
    @"i16x8.extmul_high_i8x16_u": EmptyTuple,
    @"i32x4.abs": EmptyTuple,
    @"i32x4.neg": EmptyTuple,
    @"i32x4.all_true": EmptyTuple,
    @"i32x4.bitmask": EmptyTuple,
    @"i32x4.extend_low_i16x8_s": EmptyTuple,
    @"i32x4.extend_high_i16x8_s": EmptyTuple,
    @"i32x4.extend_low_i16x8_u": EmptyTuple,
    @"i32x4.extend_high_i16x8_u": EmptyTuple,
    @"i32x4.shl": EmptyTuple,
    @"i32x4.shr_s": EmptyTuple,
    @"i32x4.shr_u": EmptyTuple,
    @"i32x4.add": EmptyTuple,
    @"i32x4.sub": EmptyTuple,
    @"i32x4.mul": EmptyTuple,
    @"i32x4.min_s": EmptyTuple,
    @"i32x4.min_u": EmptyTuple,
    @"i32x4.max_s": EmptyTuple,
    @"i32x4.max_u": EmptyTuple,
    @"i32x4.dot_i16x8_s": EmptyTuple,
    @"i32x4.extmul_low_i16x8_s": EmptyTuple,
    @"i32x4.extmul_high_i16x8_s": EmptyTuple,
    @"i32x4.extmul_low_i16x8_u": EmptyTuple,
    @"i32x4.extmul_high_i16x8_u": EmptyTuple,
    @"i64x2.abs": EmptyTuple,
    @"i64x2.neg": EmptyTuple,
    @"i64x2.all_true": EmptyTuple,
    @"i64x2.bitmask": EmptyTuple,
    @"i64x2.extend_low_i32x4_s": EmptyTuple,
    @"i64x2.extend_high_i32x4_s": EmptyTuple,
    @"i64x2.extend_low_i32x4_u": EmptyTuple,
    @"i64x2.extend_high_i32x4_u": EmptyTuple,
    @"i64x2.shl": EmptyTuple,
    @"i64x2.shr_s": EmptyTuple,
    @"i64x2.shr_u": EmptyTuple,
    @"i64x2.add": EmptyTuple,
    @"i64x2.sub": EmptyTuple,
    @"i64x2.mul": EmptyTuple,
    @"i64x2.eq": EmptyTuple,
    @"i64x2.ne": EmptyTuple,
    @"i64x2.lt_s": EmptyTuple,
    @"i64x2.gt_s": EmptyTuple,
    @"i64x2.le_s": EmptyTuple,
    @"i64x2.ge_s": EmptyTuple,
    @"i64x2.extmul_low_i32x4_s": EmptyTuple,
    @"i64x2.extmul_high_i32x4_s": EmptyTuple,
    @"i64x2.extmul_low_i32x4_u": EmptyTuple,
    @"i64x2.extmul_high_i32x4_u": EmptyTuple,
    @"f32x4.abs": EmptyTuple,
    @"f32x4.neg": EmptyTuple,
    @"f32x4.sqrt": EmptyTuple,
    @"f32x4.add": EmptyTuple,
    @"f32x4.sub": EmptyTuple,
    @"f32x4.mul": EmptyTuple,
    @"f32x4.div": EmptyTuple,
    @"f32x4.min": EmptyTuple,
    @"f32x4.max": EmptyTuple,
    @"f32x4.pmin": EmptyTuple,
    @"f32x4.pmax": EmptyTuple,
    @"f64x2.abs": EmptyTuple,
    @"f64x2.neg": EmptyTuple,
    @"f64x2.sqrt": EmptyTuple,
    @"f64x2.add": EmptyTuple,
    @"f64x2.sub": EmptyTuple,
    @"f64x2.mul": EmptyTuple,
    @"f64x2.div": EmptyTuple,
    @"f64x2.min": EmptyTuple,
    @"f64x2.max": EmptyTuple,
    @"f64x2.pmin": EmptyTuple,
    @"f64x2.pmax": EmptyTuple,
    @"i32x4.trunc_sat_f32x4_s": EmptyTuple,
    @"i32x4.trunc_sat_f32x4_u": EmptyTuple,
    @"f32x4.convert_i32x4_s": EmptyTuple,
    @"f32x4.convert_i32x4_u": EmptyTuple,
    @"i32x4.trunc_sat_f64x2_s_zero": EmptyTuple,
    @"i32x4.trunc_sat_f64x2_u_zero": EmptyTuple,
    @"f64x2.convert_low_i32x4_s": EmptyTuple,
    @"f64x2.convert_low_i32x4_u": EmptyTuple,
};
